name: flashcards
description: A cross-platform flashcard app with offline-first storage.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.0
  provider: ^6.0.0

flutter:
  uses-material-design: true
